#version 450
// out[i] = textureLod(cube, in[i].xyz, 0)
layout(local_size_x = 64) in;
layout(set = 0, binding = 0) uniform samplerCube tex;
layout(std430, set = 0, binding = 1) readonly buffer In { vec4 inp[]; };
layout(std430, set = 0, binding = 2) writeonly buffer Out { vec4 outp[]; };
layout(push_constant) uniform PC { uint n; };
void main()
{
   uint i = gl_GlobalInvocationID.x;
   if (i >= n)
      return;
   outp[i] = textureLod(tex, inp[i].xyz, 0.0);
}
