#version 450
// out[i] = textureGrad(tex, in[i].xy, (in[i].z, 0), (0, in[i].w))
layout(local_size_x = 64) in;
layout(set = 0, binding = 0) uniform sampler2D tex;
layout(std430, set = 0, binding = 1) readonly buffer In { vec4 inp[]; };
layout(std430, set = 0, binding = 2) writeonly buffer Out { vec4 outp[]; };
layout(push_constant) uniform PC { uint n; };
void main()
{
   uint i = gl_GlobalInvocationID.x;
   if (i >= n)
      return;
   vec4 c = inp[i];
   outp[i] = textureGrad(tex, c.xy, vec2(c.z, 0.0), vec2(0.0, c.w));
}
