#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(buffer_reference, std430, buffer_reference_align = 8) buffer SrcBuf {
    uint data[];
};

layout(buffer_reference, std430, buffer_reference_align = 8) buffer DstBuf {
    uint data[];
};

layout(buffer_reference, std430, buffer_reference_align = 8) buffer PtrBuf {
    SrcBuf src;
};

layout(push_constant) uniform PushConstants {
    uvec2 dst_addr;
    uvec2 ptr_buf_addr;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    DstBuf dst = DstBuf(pc.dst_addr);
    PtrBuf ptr_buf = PtrBuf(pc.ptr_buf_addr);
    SrcBuf src = ptr_buf.src;
    dst.data[i] = (src.data[i] ^ 0x5A5A0000u) + i;
}
