#version 460
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer OutBuf {
    uint data[];
} out_buf;

layout(set = 0, binding = 1, std430) readonly buffer In {
    uint v;
} ins[];

void main()
{
    uint i = gl_GlobalInvocationID.x;
    out_buf.data[i] = ins[nonuniformEXT(i % 8u)].v + i;
}
