#version 460
#extension GL_EXT_scalar_block_layout : require

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct S {
    vec3 a;
    uint b;
    uvec3 c;
};

layout(scalar, set = 0, binding = 1) readonly buffer In {
    S s[];
};

layout(std430, set = 0, binding = 0) buffer OutBuf {
    uint data[];
} out_buf;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    out_buf.data[4u * i + 0u] = floatBitsToUint(s[i].a.y);
    out_buf.data[4u * i + 1u] = s[i].b;
    out_buf.data[4u * i + 2u] = s[i].c.z;
    out_buf.data[4u * i + 3u] = uint(s[i].a.x) + s[i].c.x;
}
