#version 460
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_samplerless_texture_functions : require
layout(local_size_x = 4) in;
layout(set = 0, binding = 0) uniform utexture2D heap[];
layout(set = 1, binding = 0, std430) readonly buffer Indices { uint idx[]; } indices;
layout(set = 1, binding = 1, std430) writeonly buffer Output { uint value[]; } output_data;
void main()
{
    uint i = gl_LocalInvocationIndex;
    output_data.value[i] = texelFetch(heap[nonuniformEXT(indices.idx[i])], ivec2(0), 0).x;
}
